#!/bin/bash
cabal configure --distdir dist-profiling --enable-executable-profiling --ghc-option=-rtsopts --ghc-option=-auto-all
cabal build --distdir dist-profiling --ghc-option=-rtsopts --ghc-option=-auto-all
