#!/bin/bash

TESTS="examples/peter/Append.core examples/peter/Factorial.core examples/peter/Raytracer.core examples/peter/SumTree.core examples/peter/TreeFlip.core examples/neil/SumSquare.core examples/imaginary/Bernouilli.core examples/imaginary/DigitsOfE2.core examples/imaginary/Exp3_8.core examples/imaginary/Primes.core examples/imaginary/RFib.core examples/imaginary/Tak.core examples/imaginary/X2N1.core"
# We can't do wheel-sieve any more (without deeds). Damn:
# examples/imaginary/Wheel-Sieve*.core 

./test $* $TESTS || exit $?
