#!/usr/bin/env python

import sys
from utilities import *

abbreviations = { "Filename" : "Test", "SC time" : "SC", "Compile time" : "Cmp.", "Run time" : "Run", "Heap size" : "Mem.", "Term size" : "Size" }
def abbreviate(header):
    return abbreviations.get(header, header)

def abbreviated(self):
    return Results(self.description, abbreviate(self.key_header), [abbreviate(header) for header in self.headers], union_dict(self.results, dict(summary_rows)))


results = Results(readfile(list_get(sys.argv, 1, '-')))
print abbreviated(results)
