#!/usr/bin/env python

import sys
from utilities import *

results_a = Results(readfile(sys.argv[1]))
results_b = Results(readfile(sys.argv[2]))

def zip_values(header, left, right):
    if header == "SC time" and left.strip() == "":
        # Supercompilation time is special because it will be missing for GHC runs
        return "(" + str(round(float(right.rstrip("s")))) + "s)"
    else:
        # Result a dimensionless number representing the "right" quantity as a fraction of the "left" quantity
        return str(round(float(right) / float(left), 2))

print Results.zipresults(lambda a, b: "'" + b + "' as a fraction of '" + a + "'", zip_values, results_a, results_b)