#!/usr/bin/env python

from utilities import *

def zip_values(header, left, right):
    if header == "SC time" and (left == "" or right == ""):
        # Supercompilation time is special because it will be missing for GHC runs
        return "(" + str(round(float((left or right).rstrip("s")))) + "s)"
    elif left == "" or right == "":
        # At least one result was unavailable
        return "N/A"
    else:
        # Result a dimensionless number representing the "right" quantity as a fraction of the "left" quantity
        return show_round(float(right) / float(left), 2)

def compare(results_a, results_b):
    return Results.zipresults(lambda a, b: "'" + b + "' as a fraction of '" + a + "'", zip_values, results_a, results_b)

if __name__ == '__main__':
    import sys
    results_a = Results(readfile(sys.argv[1]))
    results_b = Results(readfile(list_get(sys.argv, 2, '-')))
    print compare(results_a, results_b)
