#!/usr/bin/env python

import sys
from utilities import *

def summarised(self):
    mean = lambda xs: sum(xs) / len(xs)
    def lift_string(f, xs):
        try:
            return show_round(f([float(x) for x in xs]), 2)
        except ValueError, e:
            return "" # Typically happens because one of the source values is unavailable

    columns = self.columns()
    summary_rows = [(summary, dict([(header, lift_string(summarise, columns[header])) for header in self.headers])) for summary, summarise in [("Maximum", max), ("Minimum", min), ("Average", mean)]]
    return Results(self.description, self.key_header, self.headers, union_dict(self.results, dict(summary_rows)))


results = Results(readfile(list_get(sys.argv, 1, '-')))
print summarised(results)